---
- name: Cleanup handson environment
  hosts: all
  gather_facts: no
  tasks:
    - name: Delete the inventory file
      file:
        path: "{{ INVENTORY_PATH }}"
        state: absent

    - name: Collect instance info
      amazon.aws.ec2_instance_info:
        region: "{{ REGION }}"
        filters:
          "tag:role": "{{ RESOURCE_TAG_ROLE }}"
      register: ec2

    - debug: var=ec2.instances

    - name: Retrive instance ids
      set_fact:
        delete_ids: "{{ ec2.instances | community.general.json_query(query) }}"
      vars:
        query: "[*].instance_id"

    - debug: var=delete_ids

    - name: Delete instances
      amazon.aws.ec2:
        state: absent
        instance_ids: "{{ delete_ids }}"
        region: "{{ REGION }}"
      when: delete_ids | length > 0

